version: 1.0

workflows:
  android-workflow:
    name: Android Workflow
    scripts:
      - name: Install Dependencies
        script: |
          #!/bin/bash
          set -ex
          npm install
          npm run build
      - name: Build Android
        script: |
          #!/bin/bash
          set -ex
          npx cap sync android
          cd android
          chmod +x gradlew  # Add this line to change permissions
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
